# Generated by Django 6.0 on 2026-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('test', 'Prueba'), ('live', 'Produccion')], default='test', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('publishable_key', models.CharField(blank=True, max_length=255)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('starter_price_id', models.CharField(blank=True, max_length=255)),
                ('business_price_id', models.CharField(blank=True, max_length=255)),
                ('team_price_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['mode'],
            },
        ),
    ]
