# Generated by Django 6.0 on 2026-07-10 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('referrals', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_referrals', 'Can view referrals'), ('can_view_commissions', 'Can view commissions'), ('can_approve_commissions', 'Can approve commissions'), ('can_mark_commissions_paid', 'Can mark commissions paid'), ('can_export_financial_reports', 'Can export financial reports')]},
        ),
        migrations.AddField(
            model_name='commission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_referral_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_referral_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_commission', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='commission',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_commissions', to='subscriptions.subscription'),
        ),
    ]
