# Generated by Django 6.0.7 on 2026-07-10 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_agentcardsale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralnotification',
            name='event_type',
            field=models.CharField(choices=[('referral_registered', 'Referral registered'), ('company_registered', 'Company registered'), ('commission_generated', 'Commission generated'), ('commission_approved', 'Commission approved'), ('commission_paid', 'Commission paid'), ('agent_card_sale', 'Agent card sale'), ('finance_alert', 'Finance alert')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='referralnotification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='referrals_r_recipie_e9f1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='referralnotification',
            index=models.Index(fields=['event_type', 'created_at'], name='referrals_r_event_t_1749a8_idx'),
        ),
    ]
