# Generated by Django 6.0.7 on 2026-07-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_alter_referralnotification_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralnotification',
            name='event_type',
            field=models.CharField(choices=[('referral_registered', 'Referral registered'), ('company_registered', 'Company registered'), ('commission_generated', 'Commission generated'), ('commission_approved', 'Commission approved'), ('commission_paid', 'Commission paid'), ('agent_card_sale', 'Agent card sale'), ('finance_alert', 'Finance alert'), ('ai_lead', 'AI lead captured')], max_length=40),
        ),
    ]
