from django.urls import path

from .views import (
    AgentCommissionPaymentsAPIView,
    AgentCommissionsAPIView,
    AgentOverviewAPIView,
    AgentPayoutCreateAPIView,
    AgentReferralsAPIView,
    ApproveCommissionAPIView,
    BillingInvoicesAPIView,
    BillingSubscriptionAPIView,
    CustomerPortalAPIView,
    FinanceAgentDetailAPIView,
    FinanceAgentsAPIView,
    FinanceCommissionsAPIView,
    FinanceCompaniesAPIView,
    FinanceDashboardView,
    FinanceOverviewAPIView,
    FinancePaymentsAPIView,
    FinanceReportCSVView,
    FinanceRefundsAPIView,
    FinanceReportsAPIView,
    FinanceRevenueAPIView,
    FinanceSectionPageView,
    FinanceSubscriptionsAPIView,
    MarkCommissionPaidAPIView,
    RefundPaymentAPIView,
    StripeWebhookAPIView,
)


urlpatterns = [
    path("dashboard/finance/", FinanceDashboardView.as_view(), name="finance-dashboard"),
    path("dashboard/finance/revenue/", FinanceSectionPageView.as_view(section="revenue", permission_key="revenue"), name="finance-revenue"),
    path("dashboard/finance/subscriptions/", FinanceSectionPageView.as_view(section="subscriptions", permission_key="subscriptions"), name="finance-subscriptions"),
    path("dashboard/finance/companies/", FinanceSectionPageView.as_view(section="companies", permission_key="companies"), name="finance-companies"),
    path("dashboard/finance/referrals/", FinanceSectionPageView.as_view(section="referrals", permission_key="referrals"), name="finance-referrals"),
    path("dashboard/finance/commissions/", FinanceSectionPageView.as_view(section="commissions", permission_key="commissions"), name="finance-commissions"),
    path("dashboard/finance/payments/", FinanceSectionPageView.as_view(section="payments", permission_key="payments"), name="finance-payments"),
    path("dashboard/finance/refunds/", FinanceSectionPageView.as_view(section="refunds", permission_key="refunds"), name="finance-refunds"),
    path("dashboard/finance/reports/", FinanceSectionPageView.as_view(section="reports", permission_key="reports"), name="finance-reports"),
    path("dashboard/finance/audit/", FinanceSectionPageView.as_view(section="audit", permission_key="reports"), name="finance-audit"),
    path("dashboard/finance/reports/<str:report_key>.csv", FinanceReportCSVView.as_view(), name="finance-report-csv"),
    path("api/v1/finance/overview/", FinanceOverviewAPIView.as_view(), name="api-finance-overview"),
    path("api/v1/finance/revenue/", FinanceRevenueAPIView.as_view(), name="api-finance-revenue"),
    path("api/v1/finance/subscriptions/", FinanceSubscriptionsAPIView.as_view(), name="api-finance-subscriptions"),
    path("api/v1/finance/companies/", FinanceCompaniesAPIView.as_view(), name="api-finance-companies"),
    path("api/v1/finance/agents/", FinanceAgentsAPIView.as_view(), name="api-finance-agents"),
    path("api/v1/finance/agents/<int:agent_id>/", FinanceAgentDetailAPIView.as_view(), name="api-finance-agent-detail"),
    path("api/v1/finance/agents/<int:agent_id>/payouts/", AgentPayoutCreateAPIView.as_view(), name="api-finance-agent-payout-create"),
    path("api/v1/finance/commissions/", FinanceCommissionsAPIView.as_view(), name="api-finance-commissions"),
    path("api/v1/finance/commissions/<int:commission_id>/approve/", ApproveCommissionAPIView.as_view(), name="api-finance-commission-approve"),
    path("api/v1/finance/commissions/<int:commission_id>/mark-paid/", MarkCommissionPaidAPIView.as_view(), name="api-finance-commission-paid"),
    path("api/v1/finance/payments/", FinancePaymentsAPIView.as_view(), name="api-finance-payments"),
    path("api/v1/finance/refunds/", FinanceRefundsAPIView.as_view(), name="api-finance-refunds"),
    path("api/v1/finance/payments/<int:payment_id>/refund/", RefundPaymentAPIView.as_view(), name="api-finance-payment-refund"),
    path("api/v1/finance/reports/", FinanceReportsAPIView.as_view(), name="api-finance-reports"),
    path("api/v1/agent/overview/", AgentOverviewAPIView.as_view(), name="api-agent-overview"),
    path("api/v1/agent/referrals/", AgentReferralsAPIView.as_view(), name="api-agent-referrals"),
    path("api/v1/agent/commissions/", AgentCommissionsAPIView.as_view(), name="api-agent-commissions"),
    path("api/v1/agent/payments/", AgentCommissionPaymentsAPIView.as_view(), name="api-agent-payments"),
    path("api/v1/billing/subscription/", BillingSubscriptionAPIView.as_view(), name="api-billing-subscription"),
    path("api/v1/billing/invoices/", BillingInvoicesAPIView.as_view(), name="api-billing-invoices"),
    path("api/v1/billing/customer-portal/", CustomerPortalAPIView.as_view(), name="api-billing-customer-portal"),
    path("api/v1/stripe/webhook/", StripeWebhookAPIView.as_view(), name="api-stripe-webhook"),
]
