from django.urls import path

from .views import (
    BlockDetailAPIView,
    BlockListCreateAPIView,
    BlockTranslationDetailAPIView,
    BlockTranslationListCreateAPIView,
    ComponentDetailAPIView,
    ComponentListCreateAPIView,
    ComponentTranslationDetailAPIView,
    ComponentTranslationListCreateAPIView,
    LayoutDetailAPIView,
    LayoutListCreateAPIView,
    PageDetailAPIView,
    PageListCreateAPIView,
    PageTranslationDetailAPIView,
    PageTranslationListCreateAPIView,
    PublicSiteAPIView,
    SectionDetailAPIView,
    SectionListCreateAPIView,
    SectionTranslationDetailAPIView,
    SectionTranslationListCreateAPIView,
    ThemeListAPIView,
    WebsiteDetailAPIView,
    WebsiteListCreateAPIView,
)


urlpatterns = [
    path("websites/", WebsiteListCreateAPIView.as_view(), name="api-website-list"),
    path("websites/<int:pk>/", WebsiteDetailAPIView.as_view(), name="api-website-detail"),
    path("pages/", PageListCreateAPIView.as_view(), name="api-page-list"),
    path("pages/<int:pk>/", PageDetailAPIView.as_view(), name="api-page-detail"),
    path("layouts/", LayoutListCreateAPIView.as_view(), name="api-layout-list"),
    path("layouts/<int:pk>/", LayoutDetailAPIView.as_view(), name="api-layout-detail"),
    path("sections/", SectionListCreateAPIView.as_view(), name="api-section-list"),
    path("sections/<int:pk>/", SectionDetailAPIView.as_view(), name="api-section-detail"),
    path("components/", ComponentListCreateAPIView.as_view(), name="api-component-list"),
    path("components/<int:pk>/", ComponentDetailAPIView.as_view(), name="api-component-detail"),
    path("blocks/", BlockListCreateAPIView.as_view(), name="api-block-list"),
    path("blocks/<int:pk>/", BlockDetailAPIView.as_view(), name="api-block-detail"),
    path("page-translations/", PageTranslationListCreateAPIView.as_view(), name="api-page-translation-list"),
    path("page-translations/<int:pk>/", PageTranslationDetailAPIView.as_view(), name="api-page-translation-detail"),
    path("section-translations/", SectionTranslationListCreateAPIView.as_view(), name="api-section-translation-list"),
    path("section-translations/<int:pk>/", SectionTranslationDetailAPIView.as_view(), name="api-section-translation-detail"),
    path("component-translations/", ComponentTranslationListCreateAPIView.as_view(), name="api-component-translation-list"),
    path("component-translations/<int:pk>/", ComponentTranslationDetailAPIView.as_view(), name="api-component-translation-detail"),
    path("block-translations/", BlockTranslationListCreateAPIView.as_view(), name="api-block-translation-list"),
    path("block-translations/<int:pk>/", BlockTranslationDetailAPIView.as_view(), name="api-block-translation-detail"),
    path("themes/", ThemeListAPIView.as_view(), name="api-theme-list"),
    path("public-sites/<slug:website_slug>/", PublicSiteAPIView.as_view(), name="api-public-site-home"),
    path("public-sites/<slug:website_slug>/<slug:page_slug>/", PublicSiteAPIView.as_view(), name="api-public-site-page"),
]
