# Generated by Django 6.0 on 2026-07-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0002_seed_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitecardjob',
            name='is_physical_card_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whitecardjob',
            name='physical_card_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='jobcards/scans/'),
        ),
        migrations.AddField(
            model_name='whitecardjob',
            name='physical_card_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='jobcards/scans/'),
        ),
    ]
