# Generated by Django 6.0.7 on 2026-07-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_intent',
            field=models.CharField(blank=True, choices=[('company', 'Para mi empresa'), ('job', 'Para buscar trabajo'), ('agent', 'Agente de Cardbook')], max_length=20),
        ),
    ]
