# Generated by Django 5.1.15 on 2026-07-03 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_category_company_city_company_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('service_card', 'Service card'), ('image_card', 'Image card'), ('testimonial_card', 'Testimonial card'), ('team_member', 'Team member'), ('gallery_item', 'Gallery item'), ('faq_item', 'FAQ item'), ('button_group', 'Button group'), ('contact_info', 'Contact info'), ('social_links', 'Social links'), ('pricing_card', 'Pricing card'), ('statistic_counter', 'Statistic counter'), ('custom_component', 'Custom component')], default='custom_component', max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_homepage', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.TextField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=180)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='website_og/')),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='website_themes/')),
                ('primary_color', models.CharField(default='#0b5ed7', max_length=7)),
                ('secondary_color', models.CharField(default='#083b75', max_length=7)),
                ('accent_color', models.CharField(default='#d8a441', max_length=7)),
                ('font_family', models.CharField(default='Inter, system-ui, sans-serif', max_length=120)),
                ('button_style', models.CharField(default='pill', max_length=30)),
                ('card_style', models.CharField(default='soft', max_length=30)),
                ('navbar_style', models.CharField(default='clean', max_length=30)),
                ('footer_style', models.CharField(default='dark', max_length=30)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('rich_text', 'Rich text'), ('image', 'Image'), ('video', 'Video'), ('icon', 'Icon'), ('button', 'Button'), ('link', 'Link'), ('phone', 'Phone'), ('email', 'Email'), ('address', 'Address'), ('map', 'Map'), ('embed', 'Embed'), ('social_url', 'Social URL'), ('custom', 'Custom')], default='text', max_length=40)),
                ('key', models.CharField(max_length=80)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website_blocks/')),
                ('video', models.FileField(blank=True, null=True, upload_to='website_videos/')),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('url', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='websitebuilder.component')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_type', models.CharField(choices=[('full_width', 'Full width'), ('boxed', 'Boxed'), ('sidebar_left', 'Sidebar left'), ('sidebar_right', 'Sidebar right'), ('landing_page', 'Landing page'), ('portfolio', 'Portfolio'), ('business_profile', 'Business profile')], default='full_width', max_length=40)),
                ('name', models.CharField(default='Default layout', max_length=120)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='websitebuilder.page')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('banner', 'Banner'), ('services', 'Services'), ('gallery', 'Gallery'), ('team', 'Team'), ('testimonials', 'Testimonials'), ('clients', 'Clients'), ('logos', 'Logos'), ('cta', 'CTA'), ('contact_form', 'Contact form'), ('map', 'Map'), ('faq', 'FAQ'), ('footer', 'Footer'), ('custom', 'Custom')], default='custom', max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('background_color', models.CharField(blank=True, max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='website_sections/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='websitebuilder.layout')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='component',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='websitebuilder.section'),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('subdomain', models.SlugField(blank=True, max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='website_favicons/')),
                ('primary_color', models.CharField(default='#0b5ed7', max_length=7)),
                ('secondary_color', models.CharField(default='#083b75', max_length=7)),
                ('accent_color', models.CharField(default='#d8a441', max_length=7)),
                ('font_family', models.CharField(default='Inter, system-ui, sans-serif', max_length=120)),
                ('default_language', models.CharField(choices=[('es', 'Espanol'), ('en', 'English'), ('fr', 'Francais'), ('pt', 'Portugues')], default='es', max_length=5)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.TextField(blank=True)),
                ('custom_css', models.TextField(blank=True)),
                ('custom_js', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder_website', to='companies.company')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='websitebuilder.theme')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='websitebuilder.website'),
        ),
        migrations.CreateModel(
            name='WebsiteClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(default='button', max_length=60)),
                ('url', models.URLField(blank=True)),
                ('language', models.CharField(default='es', max_length=5)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='websitebuilder.block')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='websitebuilder.page')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='websitebuilder.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='es', max_length=5)),
                ('referrer', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='websitebuilder.page')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='websitebuilder.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Espanol'), ('en', 'English'), ('fr', 'Francais'), ('pt', 'Portugues')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=120)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='websitebuilder.block')),
            ],
            options={
                'unique_together': {('block', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ComponentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Espanol'), ('en', 'English'), ('fr', 'Francais'), ('pt', 'Portugues')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='websitebuilder.component')),
            ],
            options={
                'unique_together': {('component', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Espanol'), ('en', 'English'), ('fr', 'Francais'), ('pt', 'Portugues')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.TextField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='websitebuilder.page')),
            ],
            options={
                'unique_together': {('page', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Espanol'), ('en', 'English'), ('fr', 'Francais'), ('pt', 'Portugues')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='websitebuilder.section')),
            ],
            options={
                'unique_together': {('section', 'language')},
            },
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('website', 'slug'), name='unique_page_slug_per_website'),
        ),
    ]
