# Generated by Django 5.1.15 on 2026-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='layout',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='custom_js_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
