# Generated by Django 5.1.15 on 2026-07-09 03:38

from django.db import migrations, models


def assign_semantic_tags(apps, schema_editor):
    Section = apps.get_model("websitebuilder", "Section")
    Section.objects.filter(section_type="hero").update(html_tag="header")
    Section.objects.filter(section_type="footer").update(html_tag="footer")
    Section.objects.filter(section_type="cta").update(html_tag="section")


def reset_semantic_tags(apps, schema_editor):
    Section = apps.get_model("websitebuilder", "Section")
    Section.objects.all().update(html_tag="section")


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0002_block_is_active_layout_is_active_page_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='html_tag',
            field=models.CharField(choices=[('section', 'section - bloque tematico'), ('article', 'article - contenido independiente'), ('aside', 'aside - contenido lateral'), ('header', 'header - encabezado de seccion'), ('nav', 'nav - navegacion secundaria'), ('footer', 'footer - pie de pagina')], default='section', max_length=20),
        ),
        migrations.RunPython(assign_semantic_tags, reset_semantic_tags),
    ]
