# Generated by Django 5.1.15 on 2026-07-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0003_section_html_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='show_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='show_nav',
            field=models.BooleanField(default=True),
        ),
    ]
