# Generated by Django 6.0.7 on 2026-07-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0004_website_show_header_website_show_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('banner', 'Banner'), ('services', 'Services'), ('gallery', 'Gallery'), ('team', 'Team'), ('testimonials', 'Testimonials'), ('clients', 'Clients'), ('logos', 'Logos'), ('cta', 'CTA'), ('contact_form', 'Contact form'), ('form_builder', 'Forms Builder'), ('map', 'Map'), ('faq', 'FAQ'), ('footer', 'Footer'), ('custom', 'Custom')], default='custom', max_length=40),
        ),
    ]
