# Generated by Django 6.0.7 on 2026-07-12 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_category_company_city_company_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('success_message', models.CharField(default='Gracias. Hemos recibido tu mensaje.', max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('email', 'Email'), ('phone', 'Telefono'), ('textarea', 'Parrafo'), ('select', 'Selector'), ('checkbox', 'Checkbox'), ('number', 'Numero'), ('date', 'Fecha')], default='text', max_length=30)),
                ('placeholder', models.CharField(blank=True, max_length=160)),
                ('help_text', models.CharField(blank=True, max_length=180)),
                ('choices', models.TextField(blank=True, help_text='Una opcion por linea para campos selector.')),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_builder.formdefinition')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('sender_name', models.CharField(blank=True, max_length=160)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms_builder.formdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_form_slug_per_company'),
        ),
    ]
