# Generated by Django 5.1.15 on 2026-06-17 02:38

from django.db import migrations, models
from django.utils.text import slugify


def populate_company_slugs(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    used = set()
    for company in Company.objects.all().order_by("id"):
        base = slugify(company.name) or f"company-{company.id}"
        slug = base
        counter = 1
        while slug in used or Company.objects.filter(slug=slug).exclude(pk=company.pk).exists():
            counter += 1
            slug = f"{base}-{counter}"
        used.add(slug)
        company.slug = slug
        company.save(update_fields=["slug"])


def drop_slug_like_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP INDEX IF EXISTS companies_company_slug_cddc66aa_like")


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.RunPython(populate_company_slugs, migrations.RunPython.noop),
        migrations.RunPython(drop_slug_like_index, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
