# Generated by Django 6.0 on 2026-09-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_category_company_city_company_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_appointments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_directions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_quote_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='show_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_website',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
