# Generated by Django 5.1.15 on 2026-06-25 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0006_businesscard_name_font_businesscard_name_size_and_more'),
        ('companies', '0002_company_category_company_city_company_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_in_books', to='cards.businesscard')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_in_books', to='companies.company')),
                ('digital_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_in_books', to='cards.digitalcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
