# Generated by Django 6.0.7 on 2026-07-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagentlead',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('closed', 'Cerrado'), ('converted', 'Convertido')], default='new', max_length=20),
        ),
    ]
