# Generated by Django 5.1.15 on 2026-06-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcard',
            name='qr_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='qr_dot_color',
            field=models.CharField(default='#003875', max_length=7),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='qr_marker_color',
            field=models.CharField(default='#0057b8', max_length=7),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='qr_shape',
            field=models.CharField(choices=[('diamond', 'Diamantes'), ('dot', 'Puntos'), ('square', 'Cuadros')], default='diamond', max_length=20),
        ),
    ]
