# Generated by Django 5.1.15 on 2026-06-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_digitalcard_qr_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcard',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='infaithcore_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='x_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
