# Generated by Django 5.1.15 on 2026-06-17 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_digitalcard_facebook_url_digitalcard_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tagline', models.CharField(blank=True, max_length=160, null=True)),
                ('size', models.CharField(choices=[('standard', '3.5 x 2 pulgadas')], default='standard', max_length=20)),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=20)),
                ('accent_color', models.CharField(default='#d8a441', max_length=7)),
                ('background_color', models.CharField(default='#003875', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('include_qr', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_cards', to='cards.digitalcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
