# Generated by Django 5.1.15 on 2026-06-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_businesscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
