# Generated by Django 5.1.15 on 2026-06-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_businesscard_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='name_font',
            field=models.CharField(choices=[('serif', 'Editorial'), ('sans', 'Limpia'), ('modern', 'Moderna'), ('condensed', 'Compacta')], default='serif', max_length=20),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='name_size',
            field=models.CharField(choices=[('auto', 'Automatico'), ('small', 'Pequeno'), ('medium', 'Mediano'), ('large', 'Grande')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='name_font',
            field=models.CharField(choices=[('serif', 'Editorial'), ('sans', 'Limpia'), ('modern', 'Moderna'), ('condensed', 'Compacta')], default='serif', max_length=20),
        ),
        migrations.AddField(
            model_name='digitalcard',
            name='name_size',
            field=models.CharField(choices=[('auto', 'Automatico'), ('small', 'Pequeno'), ('medium', 'Mediano'), ('large', 'Grande')], default='auto', max_length=20),
        ),
    ]
