# Generated by Django 6.0 on 2026-07-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_businesscard_name_font_businesscard_name_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='is_physical_card_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='physical_card_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_cards/scans/'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='physical_card_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_cards/scans/'),
        ),
    ]
