# Generated by Django 6.0 on 2026-07-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stripe_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commissions_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commissions_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active_subscriptions', models.PositiveIntegerField(default=0)),
                ('new_subscriptions', models.PositiveIntegerField(default=0)),
                ('cancelled_subscriptions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_start', 'period_end')},
            },
        ),
    ]
